# Generated by Django 5.0.6 on 2024-11-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_tiken',
            new_name='email_token',
        ),
    ]
