# Generated by Django 5.0.6 on 2024-11-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='minimun_amount',
            field=models.IntegerField(default=500),
        ),
    ]
